### ISSUE TITLE
Error while using it in PHPStorm

### ISSUE THREAD

**Issue by paales** [magento/marketplace-eqp#8] opened 2016-08-03 09:49 UTC
Magento 2.1, version 1.0.2. I can't get it working in PHPStorm.

Using the path`$PROJECT/vendor/magento/marketplace-eqp/MEQP1`

```
phpcs: PHP Fatal error: Uncaught PHP_CodeSniffer_Exception: Referenced sniff "Generic.Arrays.DisallowShortArraySyntax" does not exist in /vendor/squizlabs/php_codesniffer/CodeSniffer.php:847 Stack trace:
#0 /vendor/squizlabs/php_codesniffer/CodeSniffer.php(587): PHP_CodeSniffer->_expandRulesetReference(Object(SimpleXMLElement), '/Users/paul/Sit...', 0)
#1 /vendor/squizlabs/php_codesniffer/CodeSniffer.php(435): PHP_CodeSniffer->processRuleset('/Users/paul/Sit...')
```

Using the path`$PROJECT/vendor/magento/marketplace-eqp/MEQP2`

```
phpcs: PHP Fatal error: Uncaught PHP_CodeSniffer_Exception: Referenced sniff "MEQP1.CodeAnalysis.EmptyBlock" does not exist in vendor/squizlabs/php_codesniffer/CodeSniffer.php:847 Stack trace:
#0 vendor/squizlabs/php_codesniffer/CodeSniffer.php(587): PHP_CodeSniffer->_expandRulesetReference(Object(SimpleXMLElement), '/Users/paul/Sit...', 0)
#1 vendor/squizlabs/php_codesniffer/CodeSniffer.php(435): PHP_CodeSniffer->processRuleset('/Users/paul/Sit...')
```
## Instructions how to integrate with PHPStorm to run besides the default code sniffer.

Magento 2's default code sniffer is ran from here:
`$PROJECT/dev/tests/static/testsuite/Magento/Test/Php/_files/phpcs`

Is this code sniffer meant to replace Magento's code sniffer or is it complementary? I understand they both offer a different purpose, but I see a lot of smart checks that are helpful during development.

**Comment by ed007m** [comment] 2016-08-03 14:47
@paales, thank you for reporting. When you are running MEQP1 standard the problem is in PHP_CodeSniffer version in magento composer.json file. It 's  "1.5.3". In that version there was no "Generic.Arrays.DisallowShortArraySyntax" sniff. This version of Code Sniffer is used for sniffs that are located here:
 `$PROJECT/dev/tests/static/testsuite/Magento/Test/Php/_files/phpcs`. This standard in using for core developers(and MEQP standards for third-party developers). Some of this sniffs are already transferred to MEQP standards, other will be there in the near future. We will investigate a possibility of upgrading PHP_CodeSniffer in magento composer.json file. 

For our standards required version of PHP_CodeSniffer is ">= 2.3.1". As a solution you may install PHP_CodeSniffer as a standalone application with version  ">= 2.3.1" and specify in PhpStorm path to this phpcs file. This will help you also to avoid your second issue, when you are running MEQP2 standard. In your PHP_CodeSniffer project you will need just to set paths to our coding standards (both, MEQP1 and MEQP2) and Code inspections should work.

**Comment by paales** [comment] 2016-08-04 21:46
Steps to get it MEQP2 working in PHPStorm with Magento 2:
1. Install PHP_CodeSniffer `^2.6`
2. Make references to the correct MEQP1 directly since they are not installed by default:

``` XML
    <rule ref="../MEQP1/Sniffs/CodeAnalysis/EmptyBlockSniff.php"/>
    <rule ref="../MEQP1/Sniffs/Exceptions/NamespaceSniff.php"/>
    <rule ref="../MEQP1/Sniffs/Performance/CollectionCountSniff.php"/>
    <rule ref="../MEQP1/Sniffs/Performance/FetchAllSniff.php"/>
    <rule ref="../MEQP1/Sniffs/Performance/GetFirstItemSniff.php"/>
    <rule ref="../MEQP1/Sniffs/Performance/LoopSniff.php"/>
    <rule ref="../MEQP1/Sniffs/PHP/GotoSniff.php"/>
    <rule ref="../MEQP1/Sniffs/PHP/VarSniff.php"/>
    <rule ref="../MEQP1/Sniffs/Security/DiscouragedFunctionSniff.php"/>
    <rule ref="../MEQP1/Sniffs/Security/IncludeFileSniff.php"/>
    <rule ref="../MEQP1/Sniffs/Security/LanguageConstructSniff.php"/>
    <rule ref="MEQP1.Security.LanguageConstruct.DirectOutput">
        <exclude-pattern>*.phtml</exclude-pattern>
    </rule>
    <rule ref="../MEQP1/Sniffs/SQL/RawQuerySniff.php"/>
    <rule ref="../MEQP1/Sniffs/SQL/SlowQuerySniff.php"/>
    <rule ref="../MEQP1/Sniffs/Strings/RegExSniff.php"/>
    <rule ref="../MEQP1/Sniffs/Strings/StringConcatSniff.php"/>
    <rule ref="../MEQP1/Sniffs/Strings/StringPositionSniff.php"/>
```

After these modifications and setup it works as expected:
<img width="1044" alt="schermafbeelding 2016-08-04 om 23 45 18" src="https://cloud.githubusercontent.com/assets/1244416/17419405/9076b0a4-5a9d-11e6-879d-4cc7e3eb0f8b.png">

Can these changes be incorporated in the project?

**Comment by powli** [comment] 2016-09-02 07:31
@paales: If they would change it to the relative reference in their ruleset, users that have adjusted their phpcs installed_paths will get an error.

If you have installed a seperate instance of phpcs in version `^2.6` anyway, you can just adjust the installed_paths for this instance by running
`phpcs --config-set installed_paths /path/to/marketplace-eqp`

Afterwards the MEQP2 standard should execute as expected.

**Closed as completed** 2016-09-16 12:57 UTC

**Comment by paales** [comment] 2016-09-16 13:29
@lenaorobei I'm not really sure, but I don't think https://github.com/magento/marketplace-eqp/commit/d3fd6bf04a2f1ea8950e589cb4725f81816b7e0d solves the path problems in PHPStorm? Or does it?

**Comment by lenaorobei** [comment] 2016-09-16 13:46
@paales we added the requirement to `composer.json` file `"squizlabs/php_codesniffer": ">= 2.3.1"` to ensure the efficiency of MEQP coding standard.

**Comment by paales** [comment] 2016-09-16 13:53
@lenaorobei Alright! That is good news. Does this also the issue mentioned in https://github.com/magento/marketplace-eqp/issues/8#issuecomment-237693577?

**Comment by lenaorobei** [comment] 2016-09-16 14:50
@paales for now, MEQP coding standard is incompatible with CodeSniffer, that is installed in Magento 2. So the way to make it work is to install required version.
And what about you question

> Can these changes be incorporated in the project?

CodeSniffer allows configuring custom standards, so you don't have to fix references. To make it work you should configure CodeSniffer by running `phpcs --config-set installed_paths /path/to/marketplace-eqp`

**Comment by paales** [comment] 2016-09-28 15:44
Thanks @lenaorobei. I'll try and figure it out if we can get it working in PHPStorm directly. If we're still having problems, I'll report back to you.

**Comment by lenaorobei** [comment] 2016-09-29 07:49
@paales feel free to reopen this issue if you still have problems with working in PHPStorm.

**Comment by paales** [comment] 2016-09-29 11:59
@lenaorobei Please note that I can't open the issue :)

**Comment by lenaorobei** [comment] 2016-09-29 15:17
@paales just let me know if you have any problems.
